### ISSUE TITLE
UI: Use JKI 2.0 controls?

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/AFM-Lithography#15]

**Comment by ciozi137** [comment]
might not be worth pursuing until other refactor, #16

**Comment by Monkeymerlot** [comment]
Ive had some issues with the JKI Design Palette causing a LabVIEW crash, so I would rather we hold off on adding that as a dependency until this issue is fixed.

**Comment by ciozi137** [comment]
I had that issue before but then it went away. Maybe uninstall and reinstall? Idk. I use them with the lockin and don’t have too many issues

**Comment by Monkeymerlot** [comment]
What I got so far. 
![image](https://user-images.githubusercontent.com/37567672/85184975-02b14d00-b260-11ea-8932-6e7ad3b0a056.png)
I think the next step in terms of UIs is to decouple the front end from the microscope drivers. For example, the run button doesnt actually do anything on the AFM_Lithography VI. It is solely being read (via a reference) in the AFM Drivers. 

I have a lot of work done in the Albro_refactoring branch, and I reviewed over the video that we took of the presentation and am going to finish up those small details and have someone go over it with me, and then integrate it into this program.

**Comment by ciozi137** [comment]
Looking good

**Comment by Monkeymerlot** [comment]
Fixed some spacing issues, added a background:
![image](https://user-images.githubusercontent.com/37567672/85188245-36e23900-b273-11ea-8bb7-f980dc11f0d3.png)

**Comment by ciozi137** [comment]
I would suggest same style buttons for run and stop as the help etc. also
continue with 2.0 for other controls like paths and time. Basically all.
Idk what kind of control the pattern drag and drop is

**Comment by Monkeymerlot** [comment]
You mean just icons? I put them as big because I thought that they should be larger since they are more important, but I think that a uniform bar would also be nice.
The patterns is a system listbox (I replaced it yesterday I think) and they are about as nice as it gets. I can make the text bigger though and add some pizzazz to it in the future. 
The time will have to be a string indicator since there isn't a time stamp indicator for the JKI 2.0, but that's not really an issue.
Also I will be putting up an Asylum AFM API repository/package probably this weekend for the new AFM drivers, so that will need to be hosted at somepoint (no rush because Im the only one working on the new driver...)

**Comment by ciozi137** [comment]
Yeah I was thinking just icons. And we can add the mouse-over help (I
forget what it’s called)

String indicator is good for the time

**Comment by Monkeymerlot** [comment]
Tip strip is the word you are looking for. And sounds good.

**Comment by ciozi137** [comment]
@Monkeymerlot i think we can close this issue?

**Comment by Monkeymerlot** [comment]
I still need to do the path, rectangle and funnel properties subpanels transition to JKI Flat UI 2.0 controls. Other than that most things are transitioned over.

**Comment by Monkeymerlot** [comment]
Sneak peak at custom made JKI Flat 2.0 Themed controls that are small so we can fit them on these subpanels:
![image](https://user-images.githubusercontent.com/37567672/86155164-094a8a80-bad2-11ea-9700-91c58c01aa1e.png)

This replacement will be somewhat more involved than previous control replacements.

**Comment by ciozi137** [comment]
Looks great

**Comment by Monkeymerlot** [comment]
Rectangle Edit is done:
![image](https://user-images.githubusercontent.com/37567672/86161972-13718680-badc-11ea-87e8-d0a4e8ec5943.png)
I didnt want to change the resistance package and I wanted a good looking enum so I had to typecast it to the correct type. I ran through all the values to make sure they all will be correct after typecasting and it works fine:
![image](https://user-images.githubusercontent.com/37567672/86162189-6a775b80-badc-11ea-8d36-8da5e877c5f3.png)
where Resistor Box Typedef --> Flat UI 2.0 control uses a local to ensure that any changes will still typecast correctly:
![image](https://user-images.githubusercontent.com/37567672/86162221-77944a80-badc-11ea-80d6-5dcdf36870fe.png)

**Comment by ciozi137** [comment]
Looks really nice.

**Comment by Monkeymerlot** [comment]
Comparison for Histories sake:

![image](https://user-images.githubusercontent.com/37567672/86165999-1a02fc80-bae2-11ea-9a65-3b2625514b06.png)

And finished:

![image](https://user-images.githubusercontent.com/37567672/86169430-9cda8600-bae7-11ea-8a7a-be47770636b8.png)

**Comment by Monkeymerlot** [comment]
This is a normal system. See how the text appears below ring:
![image](https://user-images.githubusercontent.com/37567672/86497068-183d7100-bd4e-11ea-9160-82aad8e5b6b1.png)
When I customize it, text will appear above control:
![image](https://user-images.githubusercontent.com/37567672/86497122-5470d180-bd4e-11ea-9636-5072a56fe149.png)
I guess this is a non issue because the functionality I was looking for is more of the hover:
![Hoverover](https://user-images.githubusercontent.com/37567672/86497313-3788ce00-bd4f-11ea-943b-2f059962ee0a.gif)
