### ISSUE TITLE
Interpolation Distance Clarification

### ISSUE THREAD

**Issue by Monkeymerlot** [levylabpitt/AFM-Lithography#54]
The interpolation seems to cause a lot of people anguish, so I have some questions about the different interpolations and what they are doing.
So, to start with there are two Interpolation values that I have been told in the past need to match otherwise you get some weird errors. This is only a thing for the Asylum AFMs though.
Here are the two on the front panel:
![image](https://user-images.githubusercontent.com/37567672/87253161-dcd62d00-c446-11ea-8571-c8a49e2e61dd.png)

Here are where they are actually used:

## AFM_Lithography:
There is only one place that uses the interpolation on the entire block diagram:
![image](https://user-images.githubusercontent.com/37567672/87253196-35a5c580-c447-11ea-9d2d-2cb92e5f2aa2.png)

and this then only wired for paths:
![image](https://user-images.githubusercontent.com/37567672/87253206-45bda500-c447-11ea-8c20-b230c1f23008.png)

This is the only place in the path tooling this is referenced:
![image](https://user-images.githubusercontent.com/37567672/87253229-7b628e00-c447-11ea-865f-2020621476f5.png)

and it is basically used for interpolation of just paths:
![image](https://user-images.githubusercontent.com/37567672/87253242-a0570100-c447-11ea-9b57-89b047bf7687.png)

So that provides a pretty decent idea of how it is being used in the Main VI. And this makes sense, as you would need to have some spacing between the points. 

## Asylum Driver
This is solely being used in the lithography run.vi:
![image](https://user-images.githubusercontent.com/37567672/87253279-faf05d00-c447-11ea-81de-4aa3e52a43a8.png)

We see that this goes to LithoObjectPoints:
(Because this VI is a little noisy, I have traced out the interpolation with a red line)
![image](https://user-images.githubusercontent.com/37567672/87253320-50c50500-c448-11ea-8c2a-10218eee055f.png)

And then the entire Lithography Object gets interpolated:
![image](https://user-images.githubusercontent.com/37567672/87253354-7e11b300-c448-11ea-98f1-4264c3154af4.png)

Here is a look into the VI that is actually doing the interpolation:
![image](https://user-images.githubusercontent.com/37567672/87253398-dc3e9600-c448-11ea-8634-c756cfb42f2a.png)

while this looks complicated, its fairly straightforward:
1. Get the total number of points (except the last one), and repeat steps 2-5 for them:
2. Get the distance from the current point to the next one
3. Divide this distance by the interpolation distance
4. Round this value and that is the number of points that needs to be between the current point and the next point (including the current point but not the next point)
5. Add the interpolation distance times the iteration count to the current point (recall iteration count is zero indexed, so this will include the current point no matter what (unless the interpolation distance is larger than twice as large as the point separation. I should probably add a fix for that in the future)
6. Once you go through all the points, add the last point to the array

# Overview
So it seems that there are two things going on here: 
1. The interpolation on the Main program is actually a path interpolation.
2. The interpolation on the driver is a globally applied interpolation. 

I am not sure how these actually relate, and furthermore, I dont know why we need the AFM interpolation to be globally applied? Is it because of the way that we calculate the lithography time? 
Edit: Further question: Why do they need to be identical? Is it because of the potential problem I laid out in point 5 above?

**Comment by aditi-nethwewala** [comment]
@Monkeymerlot I believe @Yh-lab can give the best answer for this. As per my understanding, the global interpolation is for all objects, funnels, rectangles (of different sizes) and paths.I can imagine interpolation being helpful for a number of reasons, like for smooth writing, ultimate lithography time is just a result. The reason why the two have to be same is actually true only for paths, because of the additional interpolation mentioned in point 1. The 1st interpolation does not matter for rectangles. In principle, I think it is not necessary for it to be equal, but either greater or lesser. Since it is easy to mix up lesser or greater (like I am doing now) we just keep it equal to be safe/easy to remember. I think the extra interpolation for paths might be because of the variety of paths/path shapes we write (barriers, sidegate, etc), again a question @Yh-lab can answer best.

**Comment by Yh-lab** [comment]
@aditi-nethwewala is basically correct. During the writing for path and maybe funnels it is required to set two interpolation distance equal. For rectangular only interpolation distance in the driver matters. I forget why we have this setting. But one thing I can imagine to improve is that for rectangulars only keep points on two edges. That should enough. And automatically set the interpolation distance equal for paths and funnels

**Comment by Monkeymerlot** [comment]
@Yh-lab I'm a little bit lost (sorry my parents dog woke me up early this morning). So the Main interpolation is only required for paths? And they really only need to be set equal for paths? Furthermore rectangles definitely don't need either interpolation? Also, you're suggesting that we just automatically set the interpolation distance equal for paths and funnels, and move the Main interpolation into the settings for paths?

**Comment by Yh-lab** [comment]
I am sorry my previous answer might be wrong. I will try my best to answer this question. The reason for global driver interpolation is to have a well defined writing speed for every pattern and your patterns can be a combination of paths, funnels and rectangulars. 

This goes back to another question you asked about 50000 Hz. As far as I understand, AFM itself doesn't know about "speed", it only knows about "points" or the frequency to execute commands. So the way we define speed is to give AFM equal spacing points. And AFM goes to the next point with a frequency 50000 Hz. So a faster speed means less points and slower speed means more points.

With the above knowledge, seems the global driver interpolation is needed. Imagine a case where we want to write both a path and rectangular. A rectangular from AFM lithography only have points on two edges while a path have equal distance points. Therefore to have a well defined speed for both patterns a global interpolation is needed otherwise for a rectangular the tip can move from one edge to the other in just 1/50000 s.

I think the reason we don't want interpolation for rectangular in main program is that we don't want too much data. It makes program slow.

This is what I can remember, I hope it helps you a little.

**Comment by Monkeymerlot** [comment]
The interpolation is for paths and has been changed to be on each path interpolation. The driver interpolation is what Yuhe mentioned.
