### ISSUE TITLE
G Drive Background Image part deux

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/AFM-Lithography#96]
In addition to storing a background image in the same folder as the SVG file (Issue #93 ), we want to also store a second copy in https://drive.google.com/drive/folders/1xk2aD_zsOXk5ncsqQaHh7rXQGvoAP0cS. The file name can just be surfacepic.jpg and can be overwritten each time.

**Comment by ciozi137** [comment]
@Monkeymerlot just display latest image on https://grafana.levylab.org

**Comment by ciozi137** [comment]
If you want to try it just use google sign in with your levylab email

**Comment by Monkeymerlot** [comment]
OK that is what I thought but wasn't sure. Is there a location on the computer or will I need to do some type of http request? Also would it not make more sense to post the render there? (Render is the background image with all of the paths, funnels, rects, dots etc)

**Comment by ciozi137** [comment]
Sure good idea to put the render image instead
The image can just go in the google drive location. It would be good if we can discriminate Cypher vs MFP3D

**Comment by Monkeymerlot** [comment]
After thinking about this for a bit, this is how I think I am going to implement this: I am going to keep it generic and add a "Autosave Render?" and "Autosave Render Location" controls. This data will be added and saved to the ini file. I think having a bunch of small things that are separate between the MFP-3D and the Cypher is a really bad idea, as well as putting a dependency on google drive inside of the program. Also, I feel that this data is part of the configuration of the program for a specific instrument anyways, rather than a hard-coded part of the lithography program if that makes sense.

**Comment by ciozi137** [comment]
Yes i agree it should not be hardcoded. I like the ini option

**Comment by Monkeymerlot** [comment]
Just added on the svg-background branch.
